In [1]:
from bs4 import BeautifulSoup
import requests as re_
import pandas as pd

url = 'https://coinmarketcap.com/'

crypto_context = re_.get(url)
crypto_table = BeautifulSoup(crypto_context.text, 'html.parser')

In [2]:
#Get columns title:
title_source = crypto_table.find_all('th')[1:-2]

title_list = [item.text for item in title_source]
title_list.append('TimeStamp')

print(title_list)

['#', 'Name', 'Price', '1h %', '24h %', '7d %', 'Market Cap', 'Volume(24h)', 'TimeStamp']

In [38]:
from datetime import datetime as dt_
# Find context:
body_source = crypto_table.find_all('tr')[1:10]

# Extract context:
all_context = []
for item in body_source:
    body_context = item.find_all('td')[1:-2]
    individual_row = []
    for ind, context_ in enumerate(body_context):
        if (ind == 1):
            values = context_.find_all('p')[1].text
        elif (ind == 7):
            values = context_.find_all('p')[0].text
        elif (ind == 6):
            values = context_.find_all('span')[1].text
        else:
            values = context_.text
        individual_row.append(values)
    individual_row.append(dt_.now())

    all_context.append(individual_row)

df_body = pd.DataFrame(all_context)
df_body.head()

,0,1,2,3,4,5,6,7,8
0,1,BTC,"$60,335.23",0.18%,4.38%,7.02%,"$1,189,424,161,818","$41,498,266,737",2024-08-09 21:47:15.274737
1,2,ETH,"$2,613.24",0.47%,6.10%,16.81%,"$313,860,240,112","$21,945,321,924",2024-08-09 21:47:15.275743
2,3,USDT,$1.00,0.01%,0.01%,0.12%,"$115,442,517,032","$67,467,554,164",2024-08-09 21:47:15.277749
3,4,BNB,$504.70,0.44%,2.51%,11.79%,"$73,634,307,081","$1,717,647,207",2024-08-09 21:47:15.279743
4,5,SOL,$154.45,0.92%,1.26%,5.31%,"$72,025,460,383","$4,253,812,371",2024-08-09 21:47:15.281738

In [35]:
df_body.columns = title_list

df_body.index = df_body['#']
df_body = df_body.drop(columns=['#'])

df_body.head()

,Name,Price,1h %,24h %,7d %,Market Cap,Volume(24h),TimeStamp
#,,,,,,,,
1,BTC,"$60,335.23",0.18%,4.38%,7.02%,"$1,189,424,161,818","$41,498,266,737",2024-08-09 21:36:25.025759
2,ETH,"$2,613.24",0.47%,6.10%,16.81%,"$313,860,240,112","$21,945,321,924",2024-08-09 21:36:25.026759
3,USDT,$1.00,0.01%,0.01%,0.12%,"$115,442,517,032","$67,467,554,164",2024-08-09 21:36:25.028760
4,BNB,$504.70,0.44%,2.51%,11.79%,"$73,634,307,081","$1,717,647,207",2024-08-09 21:36:25.032763
5,SOL,$154.45,0.92%,1.26%,5.31%,"$72,025,460,383","$4,253,812,371",2024-08-09 21:36:25.034761

In [36]:
# Extract to csv file

filename = './crypto_challenge.csv'
df_body.to_csv(filename)